package by.fpmi.web.command;

public enum Commands {
    MAIN_PAGE,
    ORDER_PROJECT,
    VIEW_PROJECT,
    MAIN,
    VIEW_WORKERS_PAGE,
    VIEW_PROJECT_PAGE,
    ORDER_PROJECT_PAGE, LOGIN_PAGE, LOGIN, REGISTER_PAGE, REGISTER, ADMIN_PAGE, VIEW_WORKERS
}
